version: "3.8"


volumes:
    mysql_data:
        driver: local

services:
    mysql:
        image: mysql
        volumes:
        - mysql_data:/var/lib/mysql
        environment:
        - MYSQL_ROOT_PASSWORD=task_crud
        - MYSQL_DATABASE=task_crud
        - MYSQL_USER=task
        - MYSQL_PASSWORD=task
        ports:
        - "3306:3306"
        volumes:
        - mysql_data:/var/lib/mysql
    keycloak:
        image: jboss/keycloak
        command: 
            -Djboss.socket.binding.port-offset=100
        environment:
            DB_VENDOR: MYSQL
            DB_ADDR: mysql
            DB_DATABASE: task_crud
            DB_USER: task
            DB_PASSWORD: task
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
        ports:
        - "8180:8180"
        depends_on:
        - mysql
